# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml
stages:
- stage: deploy
  jobs:
  - deployment: DeployWeb
    displayName: deploy Web App
    pool:test1
      vmImage: 'Ubuntu-latest'
    # creates an environment if it doesn't exist
    environment: 'test1'
    strategy:
      runOnce:
        deploy:
          steps:
          - script: echo Hello world