# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml
trigger: none
jobs:
- deployment: VMDeploy
  displayName: Deploy to VM
  environment: 
    name: testVM.VMIAOT030VM
    resourceType: VirtualMachine
    tags: testtag 
  strategy:
    runOnce:
      deploy:   
          steps:
          - script: echo "Hello world"
